version: "3.4"
configs:
  prometheus_config_1_0_0:
    file: ./prometheus.yml
services:
  # mysql service
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    ports:
      - "3316:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  # prometheus service
  prometheus:
    image: prom/prometheus:v2.15.2
    configs:
      - source: prometheus_config_1_0_0
        target: /etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus
  # Grafana 
  grafana:
    image: grafana/grafana:6.6.0
    environment:
      GF_INSTALL_PLUGINS: natel-plotly-panel
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
